version: "2"
run:
  concurrency: 6
  modules-download-mode: readonly
linters:
  default: all
  disable:
    - canonicalheader
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - dupl
    - dupword
    - err113
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - gosec
    - gosmopolitan
    - intrange
    - ireturn
    - lll
    - maintidx
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - perfsprint
    - predeclared
    - tagalign
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    errcheck:
      check-blank: false
    nolintlint:
      require-specific: true
      allow-unused: true
    revive:
      rules:
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - recvcheck
        path: pkg/k8s.io/
    paths:
      - swagger.go
      - contrib
      - dependencies
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - swagger.go
      - contrib
      - dependencies
      - third_party$
      - builtin$
      - examples$
